Repository wirecard/docs-toolchain, pull requests merged in 2020-01, with the labels that each got.

#13 Test stage
  .github/workflows/linting.yml
  .github/workflows/testing.yml
  .rubocop.yml
  Rakefile
  dependencies/Gemfile
  stages/test/ruby/base_extension.rb
  stages/test/ruby/cli.rb
  stages/test/ruby/extension_manager.rb
  stages/test/ruby/main.rb
  stages/test/ruby/main_module.rb
  stages/test/ruby/modules.d/id_checker.rb
  stages/test/ruby/modules.d/link_checker.rb
  stages/test/test_main.sh
  tests/ruby/main.rb
  tests/ruby/test_adocs.rb
  tests/ruby/test_cli.rb
  utils/ruby_utils.rb
Labels: essential

#20 Extensions/IdChecker
  Rakefile
  stages/test/ruby/base_extension.rb
  stages/test/ruby/main_module.rb
  stages/test/ruby/modules.d/id_checker.rb
  stages/test/ruby/modules.d/link_checker.rb
  tests/ruby/README.md
  tests/ruby/main.rb
  tests/ruby/test_adocs.rb
  tests/ruby/test_extensions.rb
Labels: essential, extension

#24 optparse
  stages/test/ruby/cli.rb
  stages/test/ruby/main_module.rb
  tests/ruby/test_cli.rb
  tests/ruby/test_extensions.rb
Labels: enhancement

#27 Pattern blacklist
  stages/test/main_module.rb
  stages/test/modules.d/pattern_blacklist.rb
  tests/ruby/test_extensions.rb
Labels: extension

#28 Stage/build
  .gitignore
  Rakefile
  stages/build/build.rb
  stages/build/build_main.sh
  stages/build/cli.rb
  stages/build/main.rb
  stages/test/cli.rb
  stages/test/main_module.rb
  tests/ruby/main.rb
  tests/ruby/test_cli_build.rb
  tests/ruby/test_cli_test.rb
  utils/ruby_utils.rb
Labels: essential

#33 Config manager
  config/default.yaml
  lib/config_manager.rb
  lib/extension_manager.rb
  lib/stages/test.rb
  test/main.rb
  test/test_config_manager.rb
  test/test_extension_manager.rb
  test/util.rb
  utils/frontend/js_combine.js
  utils/js/modules/common.js
Labels: essential

#39 Documentation
  .gitignore
  .inch.yml
  .reek.yml
  .rubocop.yml
  Gemfile
  README.md
  Rakefile
  lib/base_extension.rb
  lib/cli.rb
  lib/config_manager.rb
  lib/extension_manager.rb
  lib/extensions.d/id_checker.rb
  lib/extensions.d/link_checker.rb
  lib/extensions.d/pattern_blacklist.rb
  lib/log/log.rb
  lib/notify/slack.rb
  lib/stages/build.rb
  lib/stages/test.rb
  lib/utils.rb
  lib/utils/git.rb
  test/test_extension_manager.rb
  test/test_extensions.rb
  test/test_slack.rb
Labels: documentation, essential

#45 Unit test update
  .github/workflows/main.yml
  bin/test.rb
  config/default.yaml
  lib/base_extension.rb
  lib/extension_manager.rb
  lib/log/log.rb
  lib/stages/test.rb
  lib/utils.rb
  lib/utils/git.rb
  lib/utils/string.rb
  test/main.rb
  test/test_cli_build.rb
  test/test_cli_test.rb
  test/test_extensions.rb
  test/test_git.rb
  test/test_log.rb
  test/test_string.rb
  test/util.rb
Labels: enhancement

#47 Extensions/If Checker
  lib/extensions.d/if_checker.rb
  lib/stages/test.rb
  test/test_extensions.rb
  test/util.rb
Labels: essential, extension

#48 Fix logging dependency chain
  bin/build.rb
  lib/log/log.rb
  lib/stages/build.rb
  lib/stages/test.rb
  lib/utils.rb
Labels: bug
